# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/flora/communicator/grpc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'src/flora/communicator/grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!src/flora/communicator/grpc.proto\x12\x16src.flora.communicator\"\x0e\n\x0c\x45mptyRequest\"\x1f\n\nClientInfo\x12\x11\n\tclient_id\x18\x01 \x01(\t\"x\n\x12\x41ggregationRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x37\n\x0btensor_dict\x18\x02 \x01(\x0b\x32\".src.flora.communicator.TensorDict\x12\x16\n\x0ereduction_type\x18\x03 \x01(\t\"^\n\x11OperationResponse\x12\x37\n\x0btensor_dict\x18\x01 \x01(\x0b\x32\".src.flora.communicator.TensorDict\x12\x10\n\x08is_ready\x18\x02 \x01(\x08\"!\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"B\n\nTensorDict\x12\x34\n\x07\x65ntries\x18\x01 \x03(\x0b\x32#.src.flora.communicator.TensorEntry\"i\n\x0bTensorEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x03(\x05\x12\r\n\x05\x64type\x18\x04 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x05 \x01(\t\x12\x11\n\tdata_size\x18\x06 \x01(\x05\x32\xa1\x03\n\nGrpcServer\x12\x62\n\x11GetBroadcastState\x12\".src.flora.communicator.ClientInfo\x1a).src.flora.communicator.OperationResponse\x12j\n\x14SubmitForAggregation\x12*.src.flora.communicator.AggregationRequest\x1a&.src.flora.communicator.StatusResponse\x12\x65\n\x14GetAggregationResult\x12\".src.flora.communicator.ClientInfo\x1a).src.flora.communicator.OperationResponse\x12\\\n\x0eRegisterClient\x12\".src.flora.communicator.ClientInfo\x1a&.src.flora.communicator.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.flora.communicator.grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=61
  _globals['_EMPTYREQUEST']._serialized_end=75
  _globals['_CLIENTINFO']._serialized_start=77
  _globals['_CLIENTINFO']._serialized_end=108
  _globals['_AGGREGATIONREQUEST']._serialized_start=110
  _globals['_AGGREGATIONREQUEST']._serialized_end=230
  _globals['_OPERATIONRESPONSE']._serialized_start=232
  _globals['_OPERATIONRESPONSE']._serialized_end=326
  _globals['_STATUSRESPONSE']._serialized_start=328
  _globals['_STATUSRESPONSE']._serialized_end=361
  _globals['_TENSORDICT']._serialized_start=363
  _globals['_TENSORDICT']._serialized_end=429
  _globals['_TENSORENTRY']._serialized_start=431
  _globals['_TENSORENTRY']._serialized_end=536
  _globals['_GRPCSERVER']._serialized_start=539
  _globals['_GRPCSERVER']._serialized_end=956
# @@protoc_insertion_point(module_scope)
