# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.flora.communicator import grpc_pb2 as src_dot_flora_dot_communicator_dot_grpc__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/flora/communicator/grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GrpcServerStub(object):
    """Service definition for central aggregation server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBroadcastState = channel.unary_unary(
                '/src.flora.communicator.GrpcServer/GetBroadcastState',
                request_serializer=src_dot_flora_dot_communicator_dot_grpc__pb2.ClientInfo.SerializeToString,
                response_deserializer=src_dot_flora_dot_communicator_dot_grpc__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.SubmitForAggregation = channel.unary_unary(
                '/src.flora.communicator.GrpcServer/SubmitForAggregation',
                request_serializer=src_dot_flora_dot_communicator_dot_grpc__pb2.AggregationRequest.SerializeToString,
                response_deserializer=src_dot_flora_dot_communicator_dot_grpc__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetAggregationResult = channel.unary_unary(
                '/src.flora.communicator.GrpcServer/GetAggregationResult',
                request_serializer=src_dot_flora_dot_communicator_dot_grpc__pb2.ClientInfo.SerializeToString,
                response_deserializer=src_dot_flora_dot_communicator_dot_grpc__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.RegisterClient = channel.unary_unary(
                '/src.flora.communicator.GrpcServer/RegisterClient',
                request_serializer=src_dot_flora_dot_communicator_dot_grpc__pb2.ClientInfo.SerializeToString,
                response_deserializer=src_dot_flora_dot_communicator_dot_grpc__pb2.StatusResponse.FromString,
                _registered_method=True)


class GrpcServerServicer(object):
    """Service definition for central aggregation server
    """

    def GetBroadcastState(self, request, context):
        """Get current broadcast state from server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitForAggregation(self, request, context):
        """Submit tensors to server for aggregation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAggregationResult(self, request, context):
        """Get aggregated tensor result from server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterClient(self, request, context):
        """Register client with server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBroadcastState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBroadcastState,
                    request_deserializer=src_dot_flora_dot_communicator_dot_grpc__pb2.ClientInfo.FromString,
                    response_serializer=src_dot_flora_dot_communicator_dot_grpc__pb2.OperationResponse.SerializeToString,
            ),
            'SubmitForAggregation': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitForAggregation,
                    request_deserializer=src_dot_flora_dot_communicator_dot_grpc__pb2.AggregationRequest.FromString,
                    response_serializer=src_dot_flora_dot_communicator_dot_grpc__pb2.StatusResponse.SerializeToString,
            ),
            'GetAggregationResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAggregationResult,
                    request_deserializer=src_dot_flora_dot_communicator_dot_grpc__pb2.ClientInfo.FromString,
                    response_serializer=src_dot_flora_dot_communicator_dot_grpc__pb2.OperationResponse.SerializeToString,
            ),
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=src_dot_flora_dot_communicator_dot_grpc__pb2.ClientInfo.FromString,
                    response_serializer=src_dot_flora_dot_communicator_dot_grpc__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'src.flora.communicator.GrpcServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('src.flora.communicator.GrpcServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GrpcServer(object):
    """Service definition for central aggregation server
    """

    @staticmethod
    def GetBroadcastState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.flora.communicator.GrpcServer/GetBroadcastState',
            src_dot_flora_dot_communicator_dot_grpc__pb2.ClientInfo.SerializeToString,
            src_dot_flora_dot_communicator_dot_grpc__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitForAggregation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.flora.communicator.GrpcServer/SubmitForAggregation',
            src_dot_flora_dot_communicator_dot_grpc__pb2.AggregationRequest.SerializeToString,
            src_dot_flora_dot_communicator_dot_grpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAggregationResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.flora.communicator.GrpcServer/GetAggregationResult',
            src_dot_flora_dot_communicator_dot_grpc__pb2.ClientInfo.SerializeToString,
            src_dot_flora_dot_communicator_dot_grpc__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.flora.communicator.GrpcServer/RegisterClient',
            src_dot_flora_dot_communicator_dot_grpc__pb2.ClientInfo.SerializeToString,
            src_dot_flora_dot_communicator_dot_grpc__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
