# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_communicator.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'grpc_communicator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17grpc_communicator.proto\x12\x16src.flora.communicator\"\x82\x01\n\x0bModelUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05\x12\x32\n\x06layers\x18\x03 \x03(\x0b\x32\".src.flora.communicator.LayerState\x12\x16\n\x0enumber_samples\x18\x04 \x01(\x05\"K\n\nLayerState\x12\x12\n\nlayer_name\x18\x01 \x01(\t\x12\x14\n\x0cparam_update\x18\x02 \x03(\x02\x12\x13\n\x0bparam_shape\x18\x03 \x03(\x05\"m\n\x0fModelParameters\x12\x14\n\x0cround_number\x18\x01 \x01(\x05\x12\x32\n\x06layers\x18\x02 \x03(\x0b\x32\".src.flora.communicator.LayerState\x12\x10\n\x08is_ready\x18\x03 \x01(\x08\"h\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\x12\x63lients_registered\x18\x03 \x01(\x05\x12\x18\n\x10updates_received\x18\x04 \x01(\x05\":\n\x0fGetModelRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05\"\x1f\n\nClientInfo\x12\x11\n\tclient_id\x18\x01 \x01(\t\"O\n\x14RegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rtotal_clients\x18\x03 \x01(\x05\x32\xb3\x02\n\rCentralServer\x12Y\n\nSendUpdate\x12#.src.flora.communicator.ModelUpdate\x1a&.src.flora.communicator.UpdateResponse\x12\x63\n\x0fGetUpdatedModel\x12\'.src.flora.communicator.GetModelRequest\x1a\'.src.flora.communicator.ModelParameters\x12\x62\n\x0eRegisterClient\x12\".src.flora.communicator.ClientInfo\x1a,.src.flora.communicator.RegistrationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_communicator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELUPDATE']._serialized_start=52
  _globals['_MODELUPDATE']._serialized_end=182
  _globals['_LAYERSTATE']._serialized_start=184
  _globals['_LAYERSTATE']._serialized_end=259
  _globals['_MODELPARAMETERS']._serialized_start=261
  _globals['_MODELPARAMETERS']._serialized_end=370
  _globals['_UPDATERESPONSE']._serialized_start=372
  _globals['_UPDATERESPONSE']._serialized_end=476
  _globals['_GETMODELREQUEST']._serialized_start=478
  _globals['_GETMODELREQUEST']._serialized_end=536
  _globals['_CLIENTINFO']._serialized_start=538
  _globals['_CLIENTINFO']._serialized_end=569
  _globals['_REGISTRATIONRESPONSE']._serialized_start=571
  _globals['_REGISTRATIONRESPONSE']._serialized_end=650
  _globals['_CENTRALSERVER']._serialized_start=653
  _globals['_CENTRALSERVER']._serialized_end=960
# @@protoc_insertion_point(module_scope)
